# ground truth validation file
gt_val: "../../data/gt_test_shuffled.hdf5"

# ground truth test file
gt_test: "../../data/gt_test_shuffled.hdf5"

gt_train: "../../data/gt_train_shuffled.hdf5"
gt_train_val:  "../../data/gt_test_shuffled.hdf5"
gt_train_test: "../../data/gt_test_shuffled.hdf5"
