# ground truth validation file
gt_val: "gt_test_shuffled.hdf5"

# ground truth test file
gt_test: "gt_test_shuffled.hdf5"

gt_train: "gt_train_shuffled.hdf5"
gt_train_val:  "gt_test_shuffled.hdf5"
gt_train_test: "gt_test_shuffled.hdf5"
